version: '3'
services:
  backend:
    build:
      context: './backend'
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/backend
    networks:
      - gmail-ai-filter-network
networks:
  gmail-ai-filter-network:
    driver: bridge
